FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD={{ mysql_root_password | default('r00tP@ss!') }}
ENV MYSQL_DATABASE={{ db_name | default('referral_db') }}
ENV MYSQL_USER={{ db_user | default('svc_db') }}
ENV MYSQL_PASSWORD={{ db_pass | default('SvcDb!401') }}

# Copy initialization SQL
COPY init.sql /docker-entrypoint-initdb.d/01-init.sql

# Enable query logging for Blue team monitoring
RUN echo "[mysqld]" >> /etc/mysql/conf.d/logging.cnf && \
    echo "general_log = 1" >> /etc/mysql/conf.d/logging.cnf && \
    echo "general_log_file = /var/log/mysql/query.log" >> /etc/mysql/conf.d/logging.cnf && \
    echo "log_output = FILE" >> /etc/mysql/conf.d/logging.cnf

EXPOSE 3306
