FROM kalilinux/kali-rolling:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get install -y -qq --no-install-recommends \
    libblas3 \
    nmap \
    sqlmap \
    hydra \
    nikto \
    smbclient \
    curl \
    wget \
    netcat-openbsd \
    openssh-client \
    dnsutils \
    tcpdump \
    python3 \
    python3-pip \
    iproute2 \
    sshpass \
    default-mysql-client \
    ldap-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["tail", "-f", "/dev/null"]
