"""OpenRange standalone package surface."""

from open_range.admit import AdmissionController, LocalAdmissionController
from open_range.admission import (
    ProbeSpec,
    ValidatorCheckReport,
    ValidatorReport,
    ValidatorStageReport,
    WitnessAction,
    WitnessBundle,
    WitnessTrace,
)
from open_range.build_config import BuildConfig, DEFAULT_BUILD_CONFIG
from open_range.cluster import BootedRelease, ExecResult, KindBackend, LiveBackend, PodSet, resolve_kubectl_cmd
from open_range.compiler import EnterpriseSaaSManifestCompiler, ManifestCompiler
from open_range.curriculum import (
    FrontierMutationPolicy,
    MutationOp,
    MutationPolicy,
    ParentScore,
    PopulationStats,
    mutation_summary,
    propose_mutations,
)
from open_range.driver import (
    EpisodeTrace,
    ScriptedRuntimeAgent,
    SessionAgent,
    TandemEpisodeDriver,
    TurnRecord,
)
from open_range.episode_config import DEFAULT_EPISODE_CONFIG, EpisodeConfig
from open_range.execution import ActionBackend, ActionExecution, PodActionBackend
from open_range.green import GreenScheduler, ScriptedGreenScheduler
from open_range.manifest import EnterpriseSaaSManifest, manifest_schema, validate_manifest
from open_range.pipeline import BuildPipeline, CandidateWorld, admit, admit_child, build
from open_range.render import EnterpriseSaaSKindRenderer, KindRenderer
from open_range.resources import (
    bundled_docs_dir,
    bundled_manifest_dir,
    bundled_manifest_names,
    bundled_manifest_path,
    bundled_schema_dir,
    load_bundled_doc,
    load_bundled_manifest,
    load_bundled_manifest_registry,
    load_bundled_schema,
    resource_root,
)
from open_range.rewards import RewardEngine
from open_range.runtime import WitnessDrivenRuntime
from open_range.runtime_types import (
    Action,
    ActionResult,
    ActorSessionState,
    Decision,
    EpisodeHandle,
    EpisodeScore,
    EpisodeState,
    Observation,
    RuntimeEvent,
    ServiceHealth,
)
from open_range.service import OpenRange
from open_range.sim import SimPlane, SimTrace, SimTurn, WitnessSimPlane
from open_range.snapshot import KindArtifacts, Snapshot, world_hash
from open_range.store import FileSnapshotStore, PoolSplit, SnapshotStore
from open_range.synth import EnterpriseSaaSWorldSynthesizer, SynthArtifacts, SynthFile, WorldSynthesizer
from open_range.weaknesses import CatalogWeaknessSeeder, WeaknessSeeder
from open_range.world_ir import (
    AssetSpec,
    CredentialSpec,
    EdgeSpec,
    GreenPersona,
    GreenWorkloadSpec,
    GroupSpec,
    HostSpec,
    LineageSpec,
    MutationBoundsSpec,
    ObjectiveSpec,
    ServiceSpec,
    UserSpec,
    WeaknessSpec,
    WorkflowSpec,
    WorkflowStepSpec,
    WorldIR,
)

__all__ = [
    "ActionResult",
    "ActorSessionState",
    "AdmissionController",
    "ActionBackend",
    "ActionExecution",
    "Action",
    "AssetSpec",
    "BuildConfig",
    "BuildPipeline",
    "BootedRelease",
    "bundled_docs_dir",
    "bundled_manifest_dir",
    "bundled_manifest_names",
    "bundled_manifest_path",
    "bundled_schema_dir",
    "CandidateWorld",
    "CatalogWeaknessSeeder",
    "CredentialSpec",
    "DEFAULT_BUILD_CONFIG",
    "DEFAULT_EPISODE_CONFIG",
    "Decision",
    "EpisodeHandle",
    "EdgeSpec",
    "EnterpriseSaaSKindRenderer",
    "EnterpriseSaaSManifest",
    "EnterpriseSaaSManifestCompiler",
    "EnterpriseSaaSWorldSynthesizer",
    "EpisodeScore",
    "EpisodeConfig",
    "EpisodeState",
    "EpisodeTrace",
    "ExecResult",
    "FileSnapshotStore",
    "FrontierMutationPolicy",
    "GreenPersona",
    "GreenScheduler",
    "GreenWorkloadSpec",
    "GroupSpec",
    "HostSpec",
    "KindArtifacts",
    "KindRenderer",
    "KindBackend",
    "LineageSpec",
    "LiveBackend",
    "load_bundled_doc",
    "load_bundled_manifest",
    "load_bundled_manifest_registry",
    "load_bundled_schema",
    "LocalAdmissionController",
    "ManifestCompiler",
    "MutationBoundsSpec",
    "MutationOp",
    "MutationPolicy",
    "ObjectiveSpec",
    "Observation",
    "OpenRange",
    "ParentScore",
    "PodActionBackend",
    "PoolSplit",
    "PodSet",
    "PopulationStats",
    "ProbeSpec",
    "RewardEngine",
    "RuntimeEvent",
    "ScriptedGreenScheduler",
    "ScriptedRuntimeAgent",
    "ServiceHealth",
    "ServiceSpec",
    "SessionAgent",
    "Snapshot",
    "SnapshotStore",
    "SimPlane",
    "SimTrace",
    "SimTurn",
    "SynthArtifacts",
    "SynthFile",
    "TandemEpisodeDriver",
    "TurnRecord",
    "UserSpec",
    "ValidatorCheckReport",
    "ValidatorReport",
    "ValidatorStageReport",
    "WeaknessSpec",
    "WeaknessSeeder",
    "WitnessSimPlane",
    "WorldSynthesizer",
    "WitnessAction",
    "WitnessBundle",
    "WitnessDrivenRuntime",
    "WitnessTrace",
    "WorkflowSpec",
    "WorkflowStepSpec",
    "WorldIR",
    "admit",
    "admit_child",
    "build",
    "manifest_schema",
    "mutation_summary",
    "propose_mutations",
    "validate_manifest",
    "resolve_kubectl_cmd",
    "resource_root",
    "world_hash",
]
