apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: openrange-cyber-offense
networking:
  disableDefaultCNI: false
  podSubnet: 192.168.0.0/16
nodes:
  - role: control-plane
    labels:
      openrange.pack: cyber-webapp-offense
      openrange.runtime: kind
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
